### ISSUE TITLE
Bug in ios6....

### ISSUE THREAD

**Issue by geogerar** [itouch2/SphereMenu#2]
Hello,
Thank you for your nice tool!
I would like to inform you for a bug when you run on ios6 (simulator and real phone )
The app crash and the problem is in  < snap = nil >
Can you please fix it?
Thank you again....

George Gerardis

**Comment by itouch2** [comment]
That's because that `UISnapBehavior : UIDynamicBehavior` is only supported by iOS 7.0 or later. It cannot run on iOS 6.

**Comment by geogerar** [comment]
Can you change a little the code....maybe with "IF" to be able to run also in iOS 6 changing the code to check if it runs in ios7.. all is ok but if it runs in ios6... run different code....

Thanks ion advance

George

**Comment by itouch2** [comment]
Sorry, you could add the "IF" logic by yourself. Then, the menu will just expand or shrink the menu items by using CABasicAnimation, and the menu items cannot be moved by finger when the menu is expanded.
